ignorePatterns:
  - '*.d.ts'
root: true
env:
  browser: true
  es2022: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:astro/recommended
  - prettier
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
overrides:
  - files: '*.astro'
    parser: 'astro-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.astro']
    rules: {}
